//
try {
    throw new Error("Oh no!");
} catch (error) {
    console.log("Found an error.");
} finally {
    // ...
}
//
